# Generated by Django 6.0.3 on 2026-04-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmpoint',
            name='is_boundary',
            field=models.BooleanField(default=True),
        ),
    ]
