# Generated by Django 6.0.3 on 2026-04-01 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_farmpoint_is_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='crop_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farm',
            name='expected_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FarmHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='image.farm')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
