# Generated by Django 6.0.3 on 2026-04-10 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_farm_crop_type_farm_expected_yield_farmhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='farmhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activity_images/'),
        ),
        migrations.AddField(
            model_name='farmhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='farmhistory',
            name='activity_type',
            field=models.CharField(choices=[('PLANTING', 'Planting'), ('SPRAYING', 'Spraying'), ('HARVEST', 'Harvest'), ('FERTILIZING', 'Fertilizing'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
